[CmdletBinding(SupportsShouldProcess=$true)]
param([Parameter(Mandatory=$true)][ValidatePattern('^https://[^/]+\.sharepoint\.com(/|$)')][string]$SiteUrl)
$ErrorActionPreference='Stop';$script:Conflicts=0
Write-Host "Target site: $SiteUrl";Connect-PnPOnline -Url $SiteUrl -Interactive
function D([string]$Name,[string]$Type,[bool]$Required=$false,[object]$Default=$null,[bool]$Indexed=$false,[bool]$Unique=$false,[string[]]$Choices=@()){return @{Name=$Name;Type=$Type;Required=$Required;Default=$Default;Indexed=$Indexed;Unique=$Unique;Choices=$Choices}}
function Ensure-Fields([string]$ListTitle,[array]$Definitions){
 $list=Get-PnPList -Identity $ListTitle -ErrorAction SilentlyContinue;if(-not $list){Write-Error "LIST NOT FOUND: $ListTitle. No replacement list was created." -ErrorAction Continue;$script:Conflicts++;return}
 $fields=@{};Get-PnPField -List $ListTitle|ForEach-Object{$fields[$_.InternalName]=$_}
 foreach($d in $Definitions){$existing=$fields[$d.Name]
  if($existing){if($existing.TypeAsString -ne $d.Type){Write-Error "SCHEMA CONFLICT: $ListTitle.$($d.Name) expected $($d.Type), found $($existing.TypeAsString). Existing field preserved." -ErrorAction Continue;$script:Conflicts++;continue};Write-Host "EXISTS: $ListTitle.$($d.Name) [$($d.Type)]"}
  else{Write-Host "PLAN: Add $($d.Type) field $ListTitle.$($d.Name)";if($PSCmdlet.ShouldProcess("$ListTitle.$($d.Name)",'Add missing field')){$args=@{List=$ListTitle;DisplayName=$d.Name;InternalName=$d.Name;Type=$d.Type;Required=$d.Required;AddToDefaultView=$false};if($d.Choices.Count){$args.Choices=$d.Choices};Add-PnPField @args|Out-Null;$existing=Get-PnPField -List $ListTitle -Identity $d.Name}}
  if($existing -and ($null -ne $d.Default -or $d.Indexed -or $d.Unique)){Write-Host "PLAN: Configure $ListTitle.$($d.Name) default/index constraints";if($PSCmdlet.ShouldProcess("$ListTitle.$($d.Name)",'Configure existing field')){$values=@{};if($null -ne $d.Default){$values.DefaultValue=if($d.Default -is [bool]){if($d.Default){'1'}else{'0'}}else{[string]$d.Default}};if($d.Indexed){$values.Indexed=$true};if($d.Unique){$values.EnforceUniqueValues=$true;$values.Indexed=$true};Set-PnPField -List $ListTitle -Identity $d.Name -Values $values|Out-Null}}
 }
}
$profiles=@(D 'ProfileKey' 'Text' $true $null $true $true;D 'IsActive' 'Boolean' $false $true $true;D 'SourceSiteUrl' 'URL';D 'SourceLibraryTitle' 'Text';D 'SourceLibraryId' 'Text';D 'DestinationSiteUrl' 'URL';D 'DestinationLibraryTitle' 'Text';D 'DestinationRootFolder' 'Text';D 'EmployeeNameFields' 'Note';D 'EmployeeIdFields' 'Note';D 'PrimaryTitleFields' 'Note';D 'StatusFields' 'Note';D 'DateFields' 'Note';D 'ApprovalFields' 'Note';D 'AttachmentFields' 'Note';D 'HiddenFields' 'Note';D 'FilenamePattern' 'Text';D 'MaxXmlSizeMb' 'Number' $false 25;D 'AllowLocalUpload' 'Boolean' $false $true;D 'AllowRawXmlPaste' 'Boolean' $false $false;D 'AllowLocalDownload' 'Boolean' $false $true;D 'AllowSharePointSave' 'Boolean' $false $true;D 'AllowGenericFields' 'Boolean' $false $true;D 'AllowedFileExtensions' 'Note';D 'ReturnUrl' 'URL';D 'ConfigurationNotes' 'Note';D 'ConfigurationVersion' 'Number' $false 1)
$sections=@('Record Overview','Form Details','Approval Status','Supporting Documents','Additional Information','Technical','Hidden');$dataTypes=@('Auto','Text','Number','Currency','Date','Date and Time','Yes/No','Email','URL','Person','Multiline Text','Attachment','Hidden')
$mappings=@(D 'ProfileKey' 'Text' $true $null $true;D 'XmlFieldName' 'Text' $true $null $true;D 'FriendlyLabel' 'Text';D 'SectionName' 'Choice' $false $null $false $false $sections;D 'DisplayOrder' 'Number';D 'IsVisible' 'Boolean' $false $true;D 'IsSearchable' 'Boolean' $false $true;D 'DataType' 'Choice' $false $null $false $false $dataTypes;D 'DisplayFormat' 'Text';D 'TrueLabel' 'Text';D 'FalseLabel' 'Text';D 'IsAttachment' 'Boolean' $false $false;D 'IsSensitive' 'Boolean' $false $false;D 'MaskInUi' 'Boolean' $false $false;D 'HelpText' 'Note';D 'IsActive' 'Boolean' $false $true $true)
$sourceModes=@('SharePointItem','SharePointUrl','SharePointPicker','LocalUpload','RawXmlPaste','BatchAdmin');$operations=@('Open Form','Parse XML','Preview Attachment','Download Copy','Save Attachment','Save All Attachments','Replace Attachment','Verify Attachment','Apply Metadata');$results=@('Success','Partial Success','Failed','Cancelled','Already Saved');$errors=@('Configuration','Validation','Permission','Not Found','Throttling','Network','XML Parsing','Attachment Decoding','Folder Creation','Upload','Verification','Metadata','Unknown')
$audit=@(D 'CorrelationId' 'Text' $false $null $true;D 'ProfileKey' 'Text' $false $null $true;D 'SourceMode' 'Choice' $false $null $false $false $sourceModes;D 'SourceSiteUrl' 'URL';D 'SourceLibrary' 'Text' $false $null $true;D 'SourceItemId' 'Text' $false $null $true;D 'SourceFileUniqueId' 'Text' $false $null $true;D 'Operation' 'Choice' $false $null $false $false $operations;D 'OperationResult' 'Choice' $false $null $false $false $results;D 'AttachmentCount' 'Number';D 'SuccessfulCount' 'Number';D 'FailedCount' 'Number';D 'ErrorCategory' 'Choice' $false $null $false $false $errors;D 'HttpStatus' 'Number';D 'SanitizedMessage' 'Note';D 'ApplicationVersion' 'Text';D 'DurationMilliseconds' 'Number';D 'CompletedOn' 'DateTime' $false $null $true)
Ensure-Fields 'InfoPathRecoveryProfiles' $profiles;Ensure-Fields 'InfoPathFieldMappings' $mappings;Ensure-Fields 'InfoPathRecoveryAudit' $audit
if($script:Conflicts){Write-Error "Provisioning completed with $script:Conflicts missing-list or schema conflict(s). Review the report; existing content was preserved." -ErrorAction Continue;exit 2}
Write-Host 'Provisioning completed successfully. Existing fields/data/permissions were preserved. No package was deployed.'
