import { SPHttpClient } from '@microsoft/sp-http';import { IRecoveryProfile,DEFAULT_LIMITS } from '../models/IRecoveryProfile';import { AUDIT_COLUMNS,AUDIT_LIST_ALIAS,AUDIT_LIST_TITLE,IConfigurationHealth,IListHealth,MAPPING_COLUMNS,MAPPING_LIST_ALIAS,MAPPING_LIST_TITLE,PROFILE_COLUMNS,PROFILE_LIST_ALIAS,PROFILE_LIST_TITLE } from '../models/IConfigurationHealth';
export interface IConfigurationListTitles{profiles:string;mappings:string;audit:string;}
export const DEFAULT_CONFIGURATION_LIST_TITLES:IConfigurationListTitles={profiles:PROFILE_LIST_TITLE,mappings:MAPPING_LIST_TITLE,audit:AUDIT_LIST_TITLE};
const aliases:{[title:string]:string}={[PROFILE_LIST_TITLE]:PROFILE_LIST_ALIAS,[MAPPING_LIST_TITLE]:MAPPING_LIST_ALIAS,[AUDIT_LIST_TITLE]:AUDIT_LIST_ALIAS};
export function escapeODataString(value:string):string{return value.replace(/'/g,"''");}
export function validateListTitle(value:string,label:string):string{const v=(value||'').trim();if(!v)throw new Error(`${label} cannot be empty.`);if(/[\\/]|^https?:|[?#]/i.test(v))throw new Error(`${label} must be a SharePoint list title, not a URL or path.`);return v;}
export function validateConfigurationSiteUrl(value:string,currentWebUrl:string):string{const requested=(value||currentWebUrl).replace(/\/$/,'');const a=new URL(requested),b=new URL(currentWebUrl);if(a.protocol!=='https:'||a.host.toLowerCase()!==b.host.toLowerCase()||a.username||a.password)throw new Error('Configuration Site URL must be an HTTPS site on the current SharePoint tenant.');return requested;}
export class SharePointProfileService{
 private readonly titles:IConfigurationListTitles;private readonly resolved:{[configured:string]:string}={};
 public constructor(private readonly http:SPHttpClient,private readonly webUrl:string,titles?:Partial<IConfigurationListTitles>){this.titles={profiles:validateListTitle(titles?.profiles||PROFILE_LIST_TITLE,'Profiles List Title'),mappings:validateListTitle(titles?.mappings||MAPPING_LIST_TITLE,'Field Mappings List Title'),audit:validateListTitle(titles?.audit||AUDIT_LIST_TITLE,'Audit List Title')};}
 public getListUrl(title:string):string{return`${this.webUrl}/_api/web/lists/getbytitle('${escapeODataString(title)}')`;}
 public async checkHealth():Promise<IConfigurationHealth>{const correlationId=this.correlationId(),results=await Promise.all([this.checkList(this.titles.profiles,PROFILE_COLUMNS),this.checkList(this.titles.mappings,MAPPING_COLUMNS),this.checkList(this.titles.audit,AUDIT_COLUMNS)]);return{configurationSiteUrl:this.webUrl,profileList:results[0],mappingList:results[1],auditList:results[2],correlationId,profilesAvailable:results[0].status==='Available'||results[0].status==='Available, but empty'||results[0].status==='Missing Required Columns'};}
 private async resolve(configuredTitle:string):Promise<{title?:string;status?:'Not Found'|'Permission Denied'|'Request Failed';itemCount?:number}>{if(this.resolved[configuredTitle])return{title:this.resolved[configuredTitle]};const first=await this.http.get(`${this.getListUrl(configuredTitle)}?$select=Title,ItemCount`,SPHttpClient.configurations.v1,{headers:{accept:'application/json;odata=nometadata','cache-control':'no-store'}});if(first.ok){const j=await first.json();this.resolved[configuredTitle]=j.Title||configuredTitle;return{title:this.resolved[configuredTitle],itemCount:Number(j.ItemCount||0)};}if(first.status===401||first.status===403)return{status:'Permission Denied'};if(first.status!==404)return{status:'Request Failed'};const alias=aliases[configuredTitle];if(!alias)return{status:'Not Found'};const fallback=await this.http.get(`${this.getListUrl(alias)}?$select=Title,ItemCount`,SPHttpClient.configurations.v1,{headers:{accept:'application/json;odata=nometadata','cache-control':'no-store'}});if(fallback.ok){const j=await fallback.json();this.resolved[configuredTitle]=j.Title||alias;return{title:this.resolved[configuredTitle],itemCount:Number(j.ItemCount||0)};}if(fallback.status===401||fallback.status===403)return{status:'Permission Denied'};return{status:fallback.status===404?'Not Found':'Request Failed'};}
 private async checkList(configuredTitle:string,required:string[]):Promise<IListHealth>{const found=await this.resolve(configuredTitle);if(!found.title)return{name:configuredTitle,configuredTitle,status:found.status||'Request Failed',missingColumns:[]};const r=await this.http.get(`${this.getListUrl(found.title)}/fields?$select=InternalName`,SPHttpClient.configurations.v1,{headers:{accept:'application/json;odata=nometadata','cache-control':'no-store'}});if(r.status===401||r.status===403)return{name:found.title,configuredTitle,resolvedTitle:found.title,status:'Permission Denied',missingColumns:[]};if(!r.ok)return{name:found.title,configuredTitle,resolvedTitle:found.title,status:'Request Failed',missingColumns:[]};const j=await r.json(),names=(j.value||[]).map((x:{InternalName:string})=>x.InternalName),missing=required.filter(x=>names.indexOf(x)<0);return{name:found.title,configuredTitle,resolvedTitle:found.title,status:missing.length?'Missing Required Columns':found.itemCount===0?'Available, but empty':'Available',missingColumns:missing,itemCount:found.itemCount};}
 public async loadActiveProfiles():Promise<IRecoveryProfile[]>{const resolved=await this.resolve(this.titles.profiles);if(!resolved.title){if(resolved.status==='Not Found')throw new Error(`The configuration list “${this.titles.profiles}” was not found on ${this.webUrl}.`);if(resolved.status==='Permission Denied')throw new Error(`You do not have permission to read the ${this.titles.profiles} list.`);throw new Error('Recovery configuration could not be loaded.');}const r=await this.http.get(`${this.getListUrl(resolved.title)}/items?$filter=IsActive eq 1&$select=*`,SPHttpClient.configurations.v1,{headers:{accept:'application/json;odata=nometadata','cache-control':'no-store'}});if(r.status===401||r.status===403)throw new Error(`You do not have permission to read the ${resolved.title} list.`);if(!r.ok)throw new Error(`Recovery configuration could not be loaded (${r.status}).`);const j=await r.json();return(j.value||[]).map((x:any)=>this.map(x));}
 private correlationId():string{return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16);});}private split(v:unknown):string[]{return typeof v==='string'?v.split(/[;,\n]/).map(x=>x.trim()).filter(Boolean):[];}private map(x:any):IRecoveryProfile{return{title:x.Title,profileKey:x.ProfileKey,isActive:!!x.IsActive,sourceSiteUrl:x.SourceSiteUrl,sourceLibraryTitle:x.SourceLibraryTitle,sourceLibraryId:x.SourceLibraryId,destinationSiteUrl:x.DestinationSiteUrl,destinationLibraryTitle:x.DestinationLibraryTitle,destinationRootFolder:x.DestinationRootFolder||'',employeeNameFields:this.split(x.EmployeeNameFields),employeeIdFields:this.split(x.EmployeeIdFields),primaryTitleFields:this.split(x.PrimaryTitleFields),statusFields:this.split(x.StatusFields),dateFields:this.split(x.DateFields),approvalFields:this.split(x.ApprovalFields),attachmentFields:this.split(x.AttachmentFields),hiddenFields:this.split(x.HiddenFields),filenamePattern:x.FilenamePattern||'',maxXmlSizeMb:x.MaxXmlSizeMb||DEFAULT_LIMITS.maxXmlSizeMb,maxNodeCount:x.MaxNodeCount||DEFAULT_LIMITS.maxNodeCount,maxDepth:x.MaxDepth||DEFAULT_LIMITS.maxDepth,maxFieldCount:x.MaxFieldCount||DEFAULT_LIMITS.maxFieldCount,maxAttachmentCount:x.MaxAttachmentCount||DEFAULT_LIMITS.maxAttachmentCount,maxAttachmentBytes:x.MaxAttachmentBytes||DEFAULT_LIMITS.maxAttachmentBytes,maxTotalAttachmentBytes:x.MaxTotalAttachmentBytes||DEFAULT_LIMITS.maxTotalAttachmentBytes,allowLocalUpload:!!x.AllowLocalUpload,allowRawXmlPaste:!!x.AllowRawXmlPaste,allowLocalDownload:!!x.AllowLocalDownload,allowSharePointSave:!!x.AllowSharePointSave,allowGenericFields:x.AllowGenericFields!==false,allowedFileExtensions:this.split(x.AllowedFileExtensions),saveRecoveredAttachments:true,saveOriginalXml:false,generateHtmlSummary:false,generatePdfSummary:false,auditFailureBlocksSave:false,returnUrl:x.ReturnUrl,configurationVersion:String(x.ConfigurationVersion||'1')};}
}
