jest.mock('@microsoft/sp-http',()=>({SPHttpClient:{configurations:{v1:{}}}}));import { AUDIT_LIST_TITLE,MAPPING_LIST_TITLE,PROFILE_COLUMNS,PROFILE_LIST_TITLE } from '../../models/IConfigurationHealth';import { escapeODataString,SharePointProfileService,validateConfigurationSiteUrl,validateListTitle } from '../../services/SharePointProfileService';
function response(status:number,body:any={}):any{return{status,ok:status>=200&&status<300,json:async()=>body};}function list(title:string,count=0):any{return response(200,{Title:title,ItemCount:count});}function fields(names:string[]):any{return response(200,{value:names.map(InternalName=>({InternalName}))});}
describe('profile configuration discovery',()=>{
 it('resolves compact titles first and escapes OData strings',()=>{const s=new SharePointProfileService({} as any,'https://sinaichicago.sharepoint.com/sites/InfoPathRecovery');expect(s.getListUrl(PROFILE_LIST_TITLE)).toContain("getbytitle('InfoPathRecoveryProfiles')");expect(s.getListUrl(MAPPING_LIST_TITLE)).toContain("getbytitle('InfoPathFieldMappings')");expect(s.getListUrl(AUDIT_LIST_TITLE)).toContain("getbytitle('InfoPathRecoveryAudit')");expect(escapeODataString("Director's Forms")).toBe("Director''s Forms");});
 it('defaults configuration URL and rejects external hosts or path-like list titles',()=>{const current='https://sinaichicago.sharepoint.com/sites/InfoPathRecovery';expect(validateConfigurationSiteUrl('',current)).toBe(current);expect(()=>validateConfigurationSiteUrl('https://example.com/site',current)).toThrow();expect(()=>validateListTitle('/lists/profiles','Profiles List Title')).toThrow();});
 it('uses configured list-title overrides',()=>{const s=new SharePointProfileService({} as any,'https://sinaichicago.sharepoint.com/sites/x',{profiles:'Custom Profiles'});expect(s.getListUrl('Custom Profiles')).toContain("getbytitle('Custom Profiles')");});
 it('tries the known spaced alias only after a genuine 404 and reports it',async()=>{const http={get:jest.fn(async(url:string)=>{if(url.includes('/fields'))return fields(url.includes('Profiles')?PROFILE_COLUMNS:['Title']);if(url.includes("getbytitle('InfoPathRecovery"))return response(404);if(url.includes("getbytitle('InfoPathField"))return response(404);return list(url.includes('Profiles')?'InfoPath Recovery Profiles':url.includes('Mappings')?'InfoPath Field Mappings':'InfoPath Recovery Audit');})};const h=await new SharePointProfileService(http as any,'https://sinaichicago.sharepoint.com/sites/x').checkHealth();expect(h.profileList.resolvedTitle).toBe('InfoPath Recovery Profiles');expect(http.get.mock.calls.some((c:any[])=>c[0].includes("getbytitle('InfoPathRecoveryProfiles')"))).toBe(true);expect(http.get.mock.calls.some((c:any[])=>c[0].includes("getbytitle('InfoPath Recovery Profiles')"))).toBe(true);});
 it.each([401,403])('does not try aliases after %s',async status=>{const http={get:jest.fn().mockResolvedValue(response(status))};const h=await new SharePointProfileService(http as any,'https://sinaichicago.sharepoint.com/sites/x').checkHealth();expect(h.profileList.status).toBe('Permission Denied');expect(http.get).toHaveBeenCalledTimes(3);});
 it('does not report expected columns as missing when a list is not found',async()=>{const http={get:jest.fn().mockResolvedValue(response(404))};const h=await new SharePointProfileService(http as any,'https://sinaichicago.sharepoint.com/sites/x',{profiles:'Unknown',mappings:'Unknown map',audit:'Unknown audit'}).checkHealth();expect(h.profileList.status).toBe('Not Found');expect(h.profileList.missingColumns).toEqual([]);});
 it('reports only genuinely missing InternalNames and empty available lists',async()=>{const almost=PROFILE_COLUMNS.slice(0,-1),http={get:jest.fn(async(url:string)=>url.includes('/fields')?fields(url.includes(PROFILE_LIST_TITLE)?almost:['Title']):list(url.includes(PROFILE_LIST_TITLE)?PROFILE_LIST_TITLE:url.includes(MAPPING_LIST_TITLE)?MAPPING_LIST_TITLE:AUDIT_LIST_TITLE,0))};const h=await new SharePointProfileService(http as any,'https://sinaichicago.sharepoint.com/sites/x').checkHealth();expect(h.profileList.status).toBe('Missing Required Columns');expect(h.profileList.missingColumns).toEqual(['ConfigurationVersion']);});
 it('reports a fully provisioned zero-item profile list as Available, but empty',async()=>{const http={get:jest.fn(async(url:string)=>url.includes('/fields')?fields(url.includes(PROFILE_LIST_TITLE)?PROFILE_COLUMNS:['Title']):list(url.includes(PROFILE_LIST_TITLE)?PROFILE_LIST_TITLE:url.includes(MAPPING_LIST_TITLE)?MAPPING_LIST_TITLE:AUDIT_LIST_TITLE,0))};const h=await new SharePointProfileService(http as any,'https://sinaichicago.sharepoint.com/sites/x').checkHealth();expect(h.profileList.status).toBe('Available, but empty');});
});
